### ISSUE TITLE
BSIS Courses

### ISSUE THREAD

**Issue by Rizzm** [EricEchemane/IQ#4]

**Comment by Rizzm** [comment]
Please include each course's course code.
Separate the BSIS and BSCPE courses.

BSIS Course 

BSIS- First year
Course
ITE 101-Computer Programming 1 (Laboratory)
ITE 101-Computer Programming 1 (Lecture)
ITE 100-Introduction to Computing (Laboratory)
ITE 100-Introduction to Computing (Lecture)
MAT 100-Mathemathics in Modern world
NSTP 100-National Service Training Program 1
PE 111-Physical Education 1
GE 104-Purposive Communication
GE 101-Understanding the Self

[Second Sem] First year, BSIS
IS 101-Fundamental of Information System 
ITE 102-Computer Programming 2 (Laboratory)
ITE 102Computer Programming 2 (Lecture)
MAT 101-Discrete Math
GE 102-Readings in Philippine History
GE 107-Ethics
NSTP 102-National Service Training Program 2
PE 112-Physical Education 2

BSIS-SECOND YEAR
First Semester
Course
Data Structure & algorithm Analysis
The Contemporary World
Science, Technology & Society
Web Application & Design
IT Infrastructure & Network Technologies 
Organization & Management Concepts
Physical Education 3

Second Semester
Course
Database Management System
Data Communication and Networking
Professional Issues in IS
Financial Management
Environmental Science
Physical Education 4
Professional Elective 1 (IT Service Management)

BSIS-THIRD YEAR
First Semester
Course
ITE 104-Informatio Management
IS 104-System Analysis and Design
DM 103-Business Process Design and Management
 IS 105-Enterprise Architecture
MAT 110 Quantitative Methods
FIL 101 - Masining na Pagpapahayag
ADV 01 - Enterprise Systems

Second semester
Course
CAP 101 IS-Capstone Project 1
DM 104-Evaluation of Business Performance
GE 111-Rizal's Life and Works
IS1 08-IT Security and Management (Lecture)
IS1 08-IT Security and Management (Laboratory)
FIL 102-Lingwistika
IS 106-IS Project Management 1
ADV 02-IT Audit and Controls

BSIS-FOURTH YEAR
FIRST SEMESTER
Course
CAP 102-IS Strategy, Management and Acquisition
IS 107-Applications Development and Emerging Technologies (Lecture)
IS 110-Applications Development and Emerging Technologies (Laboratory)
IS 109-Human Computer Interaction
GE 105-Art Appreciation
BST 100-Business Etiquette and Social Races Training
ADV 03-Professional Elective 4 (IS Innovations and New Technologies)

**Comment by EricEchemane** [comment]
Done
