### ISSUE TITLE
Edit Account

### ISSUE THREAD

**Issue by Rizzm** [EricEchemane/IQ#6]
Ma-lagay ng students yung information nila at ma-view ng professor yung information ng mga students.
Pag-ka-tapos mag take ng quiz ma-ki-kita ng  professor sa view participant yung Full name, Section year level, program, course, Rank number (kung pang ilan sila sa na unang natapos mag sagot), tapos score.
tapos palagyan ng exit yung banda sa student account kase walang exit sila pagkatapos mag quiz.
tapos paayos ng year and section lagyan mo ng symbol na agnto -
![Capture](https://user-images.githubusercontent.com/110958841/200458927-3ae15fbf-35aa-4640-9f5c-98b099663768.JPG)
4-4 dapat may symbol na (-) ganto ric

**Comment by EricEchemane** [comment]
Done
