### ISSUE TITLE
Quiz Result

### ISSUE THREAD

**Issue by Rizzm** [EricEchemane/IQ#8]
palagay ako ng result ng quiz yung questions tapos tamang sagot tapos kung saan sila mali palagay rin para makita nila. sa baba yan ng fullname, score at rank sa view score na lang ilagay para nababalikan ng mga students.

tapos kung kaya pagawa ng hindi nila pwede ma ss yung quiz.
di rin dapat na cocopy yung mga text sa quiz.
ganto sample ric sa result
![278715243_1317698115374250_2673713557252875257_n](https://user-images.githubusercontent.com/110958841/201893101-a1358a03-2ef1-494b-8c43-91d3c5f98a97.jpg)

tapos yung mga diagrams ito kahit sa weekends na to 
-Data flow Diagram
-Project architecture
-Flowchart

**Comment by EricEchemane** [comment]
done
